name = "1492-backend-dev"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[[durable_objects.bindings]]
name = "CHANNEL_DO"
class_name = "ChannelDOManagedV2"

[[durable_objects.bindings]]
name = "DIRECTORY_DO"
class_name = "DirectoryDOManagedV2"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChannelDO", "DirectoryDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ChannelDOManagedV2", "DirectoryDOManagedV2"]
